services:
    newt:
        image: fosrl/newt
        container_name: newt
        networks:
            - newt_network
        restart: unless-stopped
        environment:
            - PANGOLIN_ENDPOINT=${NEWT_PANGOLIN_ENDPOINT}
            - NEWT_ID=${NEWT_ID}
            - NEWT_SECRET=${NEWT_SECRET}

networks:
    newt_network:
        name: newt_network
        driver: bridge
