version: "3"
services:
    pairdrop:
        image: "lscr.io/linuxserver/pairdrop:latest"
        container_name: pairdrop
        restart: unless-stopped
        environment:
            - RATE_LIMIT=true # Set to true to limit clients to 1000 requests per 5 min.
            - DEBUG_MODE=false # Set to true to debug container and peer connections.
            - TZ=America/Chicago # Time Zone
        networks:
            - newt_network

networks:
    newt_network:
        external: true
